version: '3.8'

services:

  mysql-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

  # merpay-pubsub-server:
  #       build: .
  #       depends_on:
  #       - mysql-db
  #       environment:
  #           - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/merpay?characterEncoding=utf8&useSSL=false
  #           - SPRING_R2DBC_URL=r2dbc:pool:mysql://mysql-db:3306/merpay?characterEncoding=utf8&useSSL=false
  #       ports:
  #           - 8090:8090